export const ALL_TASKS_REQUEST = "ALL_TASKS_REQUEST";
export const ALL_TASKS_SUCCESS = "ALL_TASKS_SUCCESS";
export const ALL_TASKS_FAIL = "ALL_TASKS_FAIL";


export const NEW_TASK_REQUEST = "NEW_TASK_REQUEST";
export const NEW_TASK_SUCCESS = "NEW_TASK_SUCCESS";
export const NEW_TASK_RESET = "NEW_TASK_RESET";
export const NEW_TASK_FAIL = "NEW_TASK_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";